- hosts: all
  become: true
  tasks:

  - name: Print the gateway for each host when defined
    debug:
      msg: System {{ inventory_hostname }}

  - name: DEBUG
    debug:
      msg: System {{ ansible_hostname }}

  - name: Get Real ip get ip remote host
    debug:
      msg: System {{ {{ hostvars['all'].ansible_host }} }}