- hosts: all
  become: true
  tasks:

  - name: Print the gateway for each host when defined
    debug:
      msg: System {{ inventory_hostname['ansible_host'] }}

  - name: DEBUG
    debug:
      msg: System {{ ansible_hostname }}
