- hosts: all
  become: true
  tasks:

  # - name: Print the gateway for each host when defined
  #   debug:
  #     msg: System {{ hostvars[inventory_hostname].ansible_ssh_host }}

  - name: DEBUG
    debug:
      msg: "{{ ansible_host }}"
  
  - debug: var=hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2]