- hosts: all
  become: true
  tasks:

  - name: Print the gateway for each host when defined
    debug:
      msg: System {{ inventory_hostname }} has gateway {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}
