- hosts: all
  vars:
    # - cidr_allow_postgresql: ''
    - orthanc: {}
        # pg_db_name: orthanc
        # pg_user_name: orthanc
        # pg_user_passwd: ceec4eif7ya
  become: true
  tasks:

  - name: Print-out metadata for deployment
    debug:
      msg: 
      - ===============================================================
      - Ansible controller is {{ inventory_hostname }}
      - The deployment is running on {{ansible_host.split('=')[1]}}
      - The configuration orthanc 
      - "[PGSQL] CIDR allow {{ cidr_allow_postgresql }}"
      # - "[PGSQL] database name is {{ orthanc.pg_db_name}}"
      # - "[PGSQL] username is {{ orthanc.pg_user_name }}"
