- hosts: all
  vars:
    - cidr_allow_postgresql: 172.16.16.0/24
    - orthanc:
        pg_db_name: orthanc
        pg_user_name: orthanc
        pg_user_passwd: ceec4eif7ya
  become: true
  tasks:

  - name: Print-out metadata for deployment
    debug:
      msg: 
      - ===============================================================
      - Ansible controller is {{ inventory_hostname }}
      - The deployment is running on ansible_host.split('=')[1]
      - The configuration orthanc 
      - Postgresql's database name is {{ pg_db_name}}
      - Postgresql's username is {{ pg_user_name }}
