- hosts: all
  vars:
    - cidr_allow_postgresql: ''
  become: true
  tasks:
  - name: Print-out metadata for deployment
    debug:
      msg: 
      - ===============================================================
      - The deployment is running on {{ansible_host.split('=')[1]}}
      - The configuration orthanc 
      - "[PGSQL] CIDR allow {{ cidr_allow_postgresql }}"
      - "[PGSQL] database name is {{ orthanc_pg_db_name}}"
      - "[PGSQL] username is {{ orthanc_pg_username }}"
      - "[PGSQL] username is {{ orthanc_pg_passwd }}"

