- hosts: localhost
  become: true
  vars:
  - orthanc_lst_user:
      - username: demo
        password: demo
      - username: mgmt
        password: mgmt
  tasks:

  - name: Print the gateway for each host when defined
    debug:
      msg: System {{ inventory_hostname }} has gateway {{ ansible_ens18.ipv4.address }}

  - name: debug
    debug:
      msg: "{{ orthanc_lst_user }}"
