---
- hosts: localhost
  become: true
  # vars:
  # - ORTHANC__NAME:
  # - ORTHANC__STORAGE_MAX_SIZE
  # - DICOM_MODALITIES:
  #
  tasks:
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes

  - name: Install packages to allow apt to debug and trouble shoot
    apt:
      state: present
      pkg:
      - vim
      - curl
      - net-tools
      - python3-pip
      - libpq-dev
      - python-dev
      - build-essential

  - name: Install docker-compose and docker, using the 'pip3' executable
    pip:
      name: 
        - docker-compose
        - docker
        - psycopg2
      executable: pip3

  - name: Install packages to allow apt to use a repository over HTTPS
    apt:
      state: present
      pkg:
      - ca-certificates
      - gnupg
      - curl
      - gnupg
      - lsb-release

  - name: Create a directory if it does not exist
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'

  - name: "Check if path exists"
    stat:
      path: "/etc/apt/keyrings/docker.gpg"
    register: result

  - name: Add Docker's official GPG key
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    when: not result.stat.exists

  - name: Make sure universe repository is enabled
    apt_repository:
      repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu bionic stable
      state: present
      update_cache: 'True'

  - name: Run the equivalent of "apt-get update" after update repository
    apt:
      update_cache: yes

  - name: Install packages to allow apt to use a repository over HTTPS
    apt:
      state: present
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

  - name: Enable service docker, and not touch the state
    service:
      name: docker
      enabled: yes

  - name: Start service docker, if not started
    service:
      name: docker
      state: started

  - name: >
      Ping PostgreSQL server using non-default credentials and SSL
      registering the return values into the result variable for future use
    register: pgResult
    until: "pgResult is not failed"
    retries: 10
    delay: 10
    postgresql_ping:
      db: "{{orthanc_pg_db_name}}"
      login_host: "{{orthanc_pg_db_host}}"
      login_port: 5432
      login_user: "{{orthanc_pg_username}}"
      login_password: "{{orthanc_pg_passwd}}"
      ssl_mode: disable
##
  - name: Docker compose bundle of orthanc application
    when: pgResult.is_available == true
    docker_compose:
      project_name: orthanc
      definition:
        web:
          image: osimis/orthanc:22.9.0
          # volumes:
          #   - "/opt:/var/lib/orthanc/db:Z"
          ports:
            - 104:4242
            - 80:8042
          restart: 'unless-stopped'
          environment:
          # ENV Var Non-Standard
            ORTHANC__NAME: "{{ORTHANC__NAME}}"
            ORTHANC__STORAGE_MAX_SIZE: "{{ORTHANC__STORAGE_MAX_SIZE}}"
            ORTHANC__STORAGE_MAX_PATIENTS: "{{ORTHANC__STORAGE_MAX_PATIENTS}}"
            ORTHANC__SCHED_MAX_CONCURRENT_JOBS: "{{ORTHANC__SCHED_MAX_CONCURRENT_JOBS}}"
            ORTHANC__HTTP_PORT: "{{ORTHANC__HTTP_PORT}}"
            ORTHANC__DICOM_AET: "{{ORTHANC__DICOM_AET}}"
            ORTHANC__DICOM_AET_CHECK_ENABLED: "{{ORTHANC__DICOM_AET_CHECK_ENABLED}}"
            ORTHANC__DICOM_PORT: "{{ORTHANC__DICOM_PORT}}"
            ORTHANC__DICOM_SCP_TIMEOUT: "{{ORTHANC__DICOM_SCP_TIMEOUT}}"
            ORTHANC__DICOM_UNKNOWN_SOP_CLASS_ACCEPTED: "{{ORTHANC__DICOM_UNKNOWN_SOP_CLASS_ACCEPTED}}"
            ORTHANC__AC_ALLOW_REMOTE: "{{ORTHANC__AC_ALLOW_REMOTE}}"
            ORTHANC__AC_AUTHENTICATION_ENABLED: "{{ORTHANC__AC_AUTHENTICATION_ENABLED}}"
            ORTHANC__DICOM_MODALITIES: |
              {"OHIF" : [ "OHIFDCM", "viewer", 3000 ],"PACS1" : [ "ORTHANC", "orthanc", 4242 ],"FINDSCU" : [ "FINDSCU", "192.168.56.12", 1234 ]}
            ORTHANC__DICOM_ALWAYS_ALLOW_ECHO_ENABLED: "{{ORTHANC__DICOM_ALWAYS_ALLOW_ECHO_ENABLED}}"
            DICOM_ALWAYS_ALLOW_STORE_ENABLED: "{{DICOM_ALWAYS_ALLOW_STORE_ENABLED}}"
            DICOM_CHECK_MODALITY_HOST_ENABLED: "{{DICOM_CHECK_MODALITY_HOST_ENABLED}}"
            # DICOM_SCU_TIMEOUT:
            HTTP_CL_TIMEOUT: "{{HTTP_CL_TIMEOUT}}"
            HTTP_CL_VERIFY_PEERS: "{{HTTP_CL_VERIFY_PEERS}}"
            STABLE_AGE: "{{STABLE_AGE}}"
            DICOM_STRICT_AET_COMPARISON_ENABLED: "{{DICOM_STRICT_AET_COMPARISON_ENABLED}}"
            ORTHANC__REGISTERED_USERS: |
              {"orthanc": "orthanc"}
            ORTHANC__POSTGRESQL__ENABLE_INDEX: "{{ORTHANC__POSTGRESQL__ENABLE_INDEX}}"
            ORTHANC__POSTGRESQL__ENABLE_STORAGE: "{{ORTHANC__POSTGRESQL__ENABLE_STORAGE}}"
            ORTHANC__POSTGRESQL__HOST: "{{ORTHANC__POSTGRESQL__HOST}}"
            ORTHANC__POSTGRESQL__PORT: "{{ORTHANC__POSTGRESQL__PORT}}"
            ORTHANC__POSTGRESQL__DATABASE: "{{ORTHANC__POSTGRESQL__DATABASE}}"
            ORTHANC__POSTGRESQL__USERNAME: "{{ORTHANC__POSTGRESQL__USERNAME}}"
            ORTHANC__POSTGRESQL__PASSWORD: "{{ORTHANC__POSTGRESQL__PASSWORD}}"
            ORTHANC__POSTGRESQL__ENABLE_SSL: "{{ORTHANC__POSTGRESQL__ENABLE_SSL}}"
    register: output

  - debug:
      msg: 
        - "{{output}}"
        - "{{pgResult}}"