name: Orthanc-Db
on:
  push:
    branches:
      - master
    paths:
    - 'ansible/orthanc-db/**'

env:
  CIDR_ALLOW_POSTGRESQL: "172.16.16.0/24"
  ORTHANC_PGSQL_DB_NAME: orthanc
  VERSION_POSTGRESQL: 12

jobs:
  checking:
    runs-on: self-hosted
    steps:
    # Print metadata informations
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: checking.yml
          # Optional, directory where playbooks live
          directory: ./ansible/orthanc-db
          # Optional, SSH private key
          key: ${{secrets.ORTHANC_DB_SSH_PRIVATE_KEY}}
          # Optional, galaxy requirements filepath
          requirements: galaxy-requirements.yml
          # Optional, literal inventory file contents
          inventory: |
            [all]
            172.16.16.17 ansible_user=dcom
          options: |
            -e cidr_allow_postgresql=${{env.CIDR_ALLOW_POSTGRESQL}}
            -e orthanc_pg_db_name=${{env.ORTHANC_PGSQL_DB_NAME}}
            -e orthanc_pg_username=${{secrets.ORTHANC_PGSQL_USERNAME}}
            -e orthanc_pg_passwd=${{secrets.ORTHANC_PGSQL_PASSWD}}

  deploy:
    runs-on: self-hosted
    if: ${{ success() }}
    needs: checking
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: orthanc-db.yml
          # Optional, directory where playbooks live
          directory: ./ansible/orthanc-db
          # Optional, galaxy requirements filepath
          requirements: galaxy-requirements.yml
          # Optional, SSH private key
          key: ${{secrets.ORTHANC_DB_SSH_PRIVATE_KEY}}
          # Optional, literal inventory file contents
          inventory: |
            [all]
            172.16.16.17 ansible_user=dcom
          options: |
            -e cidr_allow_postgresql=${{env.CIDR_ALLOW_POSTGRESQL}}
            -e orthanc_pg_db_name=${{env.ORTHANC_PGSQL_DB_NAME}}
            -e orthanc_pg_username=${{secrets.ORTHANC_PGSQL_USERNAME}}
            -e orthanc_pg_passwd=${{secrets.ORTHANC_PGSQL_PASSWD}}
            -e version_postgresql=${{env.VERSION_POSTGRESQL}}
